/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DataGuard */

#ifndef _Included_DataGuard
#define _Included_DataGuard
#ifdef __cplusplus
extern "C" {
#endif

  /*
 * Class:     DataGuard
 * Method:    bytes
 * Signature: ([B)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_DataGuard_bytes
    (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     DataGuard
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_DataGuard_encrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     DataGuard
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_DataGuard_decrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
